// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.


// ****************************************************************************
//  avtNetCDF_ICONFileFormat.h
// ****************************************************************************

#ifndef AVT_NetCDF_ICON_FILE_FORMAT_H
#define AVT_NetCDF_ICON_FILE_FORMAT_H

#include <avtSTSDFileFormat.h>


// ****************************************************************************
//  Class: avtNetCDF_ICONFileFormat
//
//  Purpose:
//      Reads in NetCDF_ICON files as a plugin to VisIt.
//
//  Programmer: jcanton -- generated by xml2avt
//  Creation:   Thu Feb 17 16:35:48 PST 2022
//
// ****************************************************************************

class avtNetCDF_ICONFileFormat : public avtSTSDFileFormat
{
  public:
                       avtNetCDF_ICONFileFormat(const char *filename);
    virtual           ~avtNetCDF_ICONFileFormat() {;}

    //
    // This is used to return unconvention data -- ranging from material
    // information to information about block connectivity.
    //
    // virtual void      *GetAuxiliaryData(const char *var, const char *type,
    //                                  void *args, DestructorFunction &);
    //

    //
    // These are used to declare what the current time and cycle are for the
    // file.  These should only be defined if the file format knows what the
    // time and/or cycle is.
    //
    // virtual int       GetCycle(void);
    // virtual double    GetTime(void);
    //

    virtual const char    *GetType(void)   { return "NetCDF_ICON"; }
    virtual void           FreeUpResources(void); 

    virtual vtkDataSet    *GetMesh(const char *);
    virtual vtkDataArray  *GetVar(const char *);
    virtual vtkDataArray  *GetVectorVar(const char *);

  protected:
    // DATA MEMBERS

    virtual void           PopulateDatabaseMetaData(avtDatabaseMetaData *);
};


#endif
