// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

// ****************************************************************************
//  File: NetCDF_ICONPluginInfo.C
// ****************************************************************************

#include <NetCDF_ICONPluginInfo.h>

#include <visit-config.h>
VISIT_PLUGIN_VERSION(NetCDF_ICON,DBP_EXPORT)

VISIT_DATABASE_PLUGIN_ENTRY(NetCDF_ICON,General)

// ****************************************************************************
//  Method: NetCDF_ICONGeneralPluginInfo::GetName
//
//  Purpose:
//    Return the name of the database plugin.
//
//  Returns:    A pointer to the name of the database plugin.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

const char *
NetCDF_ICONGeneralPluginInfo::GetName() const
{
    return "NetCDF_ICON";
}

// ****************************************************************************
//  Method: NetCDF_ICONGeneralPluginInfo::GetVersion
//
//  Purpose:
//    Return the version of the database plugin.
//
//  Returns:    A pointer to the version of the database plugin.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

const char *
NetCDF_ICONGeneralPluginInfo::GetVersion() const
{
    return "1.0";
}

// ****************************************************************************
//  Method: NetCDF_ICONGeneralPluginInfo::GetID
//
//  Purpose:
//    Return the id of the database plugin.
//
//  Returns:    A pointer to the id of the database plugin.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

const char *
NetCDF_ICONGeneralPluginInfo::GetID() const
{
    return "NetCDF_ICON_1.0";
}
// ****************************************************************************
//  Method: NetCDF_ICONGeneralPluginInfo::EnabledByDefault
//
//  Purpose:
//    Return true if this plugin should be enabled by default; false otherwise.
//
//  Returns:    true/false
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

bool
NetCDF_ICONGeneralPluginInfo::EnabledByDefault() const
{
    return true;
}
// ****************************************************************************
//  Method: NetCDF_ICONGeneralPluginInfo::HasWriter
//
//  Purpose:
//    Return true if this plugin has a database writer.
//
//  Returns:    true/false
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

bool
NetCDF_ICONGeneralPluginInfo::HasWriter() const
{
    return false;
}
// ****************************************************************************
//  Method:  NetCDF_ICONGeneralPluginInfo::GetDefaultFilePatterns
//
//  Purpose:
//    Returns the default patterns for a NetCDF_ICON database.
//
//  Programmer:  generated by xml2info
//  Creation:    omitted
//
// ****************************************************************************
std::vector<std::string>
NetCDF_ICONGeneralPluginInfo::GetDefaultFilePatterns() const
{
    std::vector<std::string> defaultPatterns;
    defaultPatterns.push_back(".nc");

    return defaultPatterns;
}

// ****************************************************************************
//  Method:  NetCDF_ICONGeneralPluginInfo::AreDefaultFilePatternsStrict
//
//  Purpose:
//    Returns if the file patterns for a NetCDF_ICON database are
//    intended to be interpreted strictly by default.
//
//  Programmer:  generated by xml2info
//  Creation:    omitted
//
// ****************************************************************************
bool
NetCDF_ICONGeneralPluginInfo::AreDefaultFilePatternsStrict() const
{
    return false;
}

// ****************************************************************************
//  Method:  NetCDF_ICONGeneralPluginInfo::OpensWholeDirectory
//
//  Purpose:
//    Returns if the NetCDF_ICON plugin opens a whole directory name
//    instead of a single file.
//
//  Programmer:  generated by xml2info
//  Creation:    omitted
//
// ****************************************************************************
bool
NetCDF_ICONGeneralPluginInfo::OpensWholeDirectory() const
{
    return false;
}
