// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

#include <NetCDF_ICONPluginInfo.h>

VISIT_DATABASE_PLUGIN_ENTRY(NetCDF_ICON,Engine)

// ****************************************************************************
//  Method: NetCDF_ICONEnginePluginInfo::GetWriter
//
//  Purpose:
//      Sets up a NetCDF_ICON writer.
//
//  Returns:    A NetCDF_ICON writer.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************
avtDatabaseWriter *
NetCDF_ICONEnginePluginInfo::GetWriter(void)
{
    return NULL;
}

